/**
 * presence-sdk
 * Presence SDK — Service Integration Layer
 *
 * Based on:
 *   - Presence Signal Spec v0.4
 *   - Presence Verifier Spec v0.4
 *   - Presence Android Platform Appendix v0.1
 */

export { PresenceClient } from "./client.js";
export { createNonce, generateNonce, InMemoryManagedNonceStore } from "./nonce.js";
export { parsePresenceRequest, ParseError } from "./transport.js";
export {
  InMemoryLinkageStore,
  FileSystemLinkageStore,
  LinkageStoreCorruptionError,
  createPresenceSnapshot,
  createAuditEvent,
  defaultLinkCompletion,
  fileLinkageStorePath,
} from "./linkage.js";
export {
  RedisLinkageStore,
} from "./redis.js";
export {
  SqliteLinkageStore,
  renderSqliteSchema,
  SQLITE_LINKAGE_SCHEMA,
  SQLITE_LINKAGE_MAPPINGS,
  SQLITE_FIRST_MODE,
  type SqliteLinkageStoreOptions,
  type SqliteSchemaArtifact,
  type SqliteLinkageMappingRow,
} from "./sqlite-store.js";
export {
  createCompletionDescriptor,
  createCompletionSessionResponse,
  createRecoveryResponse,
  createCompletionSuccessResponse,
  createAuditEventsResponse,
  createLinkedNonceResponse,
  createLinkedProofRequestDescriptor,
  createLinkedProofRequestResponse,
  createPendingProofRequestDescriptor,
  createPendingProofRequestResponse,
  createPendingProofRequestListResponse,
  createLinkedAccountReadinessResponse,
  rewriteLinkSessionForPublicBase,
} from "./api.js";

export type {
  PresenceClientConfig,
  PresenceVerifyResult,
  LinkedVerificationResult,
  GeneratedNonce,
  NonceOptions,
  NonceIssuer,
  ManagedNonceStore,
  RawPresenceRequestBody,
  ParsedPresenceRequest,
  ServicePolicy,
  Platform,
  PresenceAttestation,
  PresenceErrorCode,
  VerifierResult,
  VerifierSuccess,
  VerifierFailure,
  LinkageStore,
  BindingPolicy,
  CreateLinkSessionOptions,
  CreateLinkSessionResult,
  CompleteLinkSessionInput,
  CompleteLinkSessionResult,
  LinkedVerificationSuccess,
  LinkedVerificationRecovery,
  LinkedProofRequestState,
  LinkedProofRequestReady,
  LinkedProofRequestUnavailable,
  CreateLinkedProofRequestResult,
  PendingProofRequestReady,
  CreatePendingProofRequestResult,
  RegisterDevicePushTokenOptions,
  RegisterDevicePushTokenResult,
  PendingProofSignalTransportPayload,
  PendingProofSignalTransportResult,
  PendingProofSignalTransport,
  LinkedAccountReadiness,
  LinkedAccountReadinessState,
  BindingMutationResult,
  LinkageAuditEvent,
  LinkSession,
  LinkedDevice,
  DevicePushTokenPlatform,
  DevicePushTokenEnvironment,
  DevicePushTokenStatus,
  DevicePushToken,
  ServiceBinding,
  PendingProofRequest,
  PendingProofSignalKind,
  PendingProofSignalDispatchState,
  PendingProofSignal,
  PendingProofSignalDispatch,
  PresenceSnapshot,
  LinkageStoreCapabilities,
  LinkCompletion,
  LinkCompletionMethod,
  PendingProofRequestStatus,
  PresenceBackendFlow,
  PresenceCompletionEndpointContract,
  CompletionEndpointDescriptor,
  PresenceCompletionDescriptor,
  PresenceCompletionSessionResponse,
  PresenceRecoveryDescriptor,
  PresenceRecoveryResponse,
  PresenceCompletionSuccessResponse,
  PresenceAdminBindingSummary,
  PresenceAdminBindingsResponse,
  PresenceAuditEventsResponse,
  PresenceLinkedNonceResponse,
  PresenceLinkedProofRequestDescriptor,
  PresenceLinkedProofRequestResponse,
  PresencePendingProofRequestDescriptor,
  PresencePendingProofRequestResponse,
  PresencePendingProofRequestListResponse,
  PresenceLinkedAccountReadinessResponse,
  LinkSessionPublicBaseOptions,
  RedisLikeClient,
} from "./types.js";
